[dependencies]
base = "0.9.8"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
itertools = "https://github.com/NatLabs/Itertools.mo#main"
ic = "0.2.1"